### PR TITLE
About Us Animation and Fix Timeline Animation

### LINKED ISSUE #45: Scrolling Animation for About Us
Make About Us section more interesting with scrolling animation:
https://ui.aceternity.com/components/container-scroll-animation

### PR DESCRIPTION
**Pull request by byue**
Had to reformat other parts of the page to accommodate animation

### CODE REVIEW

File: src/components/ui/email-submit-button.tsx [hunk 1]
```diff
@@ -47,7 +47,7 @@ const EmailSubmitButton = React.forwardRef<HTMLButtonElement, ButtonProps>(
                          disabled:cursor-not-allowed disabled:opacity-50
                          shadow-[0px_0px_1px_1px_var(--neutral-700)]
                          group-hover/input:shadow-none transition duration-400
-                         overflow-x-hidden inline-block resize-none`,
```
Comment (bryue) [inline src/components/ui/email-submit-button.tsx:50]: update PR description to include this fix

**Review by bryue — APPROVED** [review]
